### ISSUE TITLE
Show more than one maintainer per package.

### ISSUE THREAD

**Issue by jdalton** [mafintosh/node-modules#25]
For example http://node-modules.com/search?q=lodash it shows `lodash by d10` but there [are others](https://www.npmjs.com/package/lodash) and it's not listing the author (me) found in the [package.json](https://github.com/lodash/lodash/blob/3.1.0-npm/package.json#L10).

**Comment by mafintosh** [comment]
It should now show the original author (it might take a little time for the cache to invalidate).
At some point when we do a UI iteration we should figure out a good way to show all the contributors.

**Comment by jdalton** [comment]
Rock!
