### ISSUE TITLE
accessing search results over CORS

### ISSUE THREAD

**Issue by pketh** [mafintosh/node-modules#29]
Hi, 
Would you consider allowing access to search result json from other domains? 

I have an app where I'd love to be able to get npm search results using something like `"http://cors.io/?u=http://node-modules.com/search.json?q=#{query}&limit=#{limit}"` but trying to do that from my client app gives me a cors error.

If this is a thing you'd be open to, I'd be happy to write the PR to add some CORS support using `Access-Control-Allow-Origin: "*"`

Thanks for your time!

**Comment by mafintosh** [comment]
Yea! Feel free to PR that :)

**Comment by pketh** [comment]
I'm on it!
