### ISSUE TITLE
opensearch

### ISSUE THREAD

**Issue by t1st3** [mafintosh/node-modules#31]
Hi there,

I really like http://node-modules.com/ and was wondering whether you have any plan to include opensearch functionality to the website.

With opensearch, people could directly use the browser search-engine bar to search `node-modules.com`, without having to load the landing page and then type their search.

Relevant:
[home and spec for opensearch](http://www.opensearch.org)

If you find this useful, I'd be happy to open a PR for this.

And thanks a lot for this project; it's definitely awesome!

**Comment by mafintosh** [comment]
assuming its a minor change to add support for opensearch, go for it! :)
